// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses/tower-response.proto

package enchantedtowers.common.utils.proto.responses;

public final class TowerResponseOuterClass {
  private TowerResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_models_TowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_models_TowerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036responses/tower-response.proto\022\017respon" +
      "se_models\"%\n\rTowerResponse\022\t\n\001x\030\001 \001(\001\022\t\n" +
      "\001y\030\002 \001(\001B0\n,enchantedtowers.common.utils" +
      ".proto.responsesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_response_models_TowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_response_models_TowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_models_TowerResponse_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
