// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: responses/tower-response.proto

package enchantedtowers.common.utils.proto.responses;

public interface TowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response_models.TowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
