// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/player-coordinates-request.proto

package enchantedtowers.common.utils.proto.requests;

public interface PlayerCoordinatesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request_models.PlayerCoordinatesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();
}
