// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requests/player-coordinates-request.proto

package enchantedtowers.common.utils.proto.requests;

public final class PlayerCoordinatesRequestOuterClass {
  private PlayerCoordinatesRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_models_PlayerCoordinatesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_models_PlayerCoordinatesRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)requests/player-coordinates-request.pr" +
      "oto\022\016request_models\"0\n\030PlayerCoordinates" +
      "Request\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001B/\n+enchant" +
      "edtowers.common.utils.proto.requestsP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_request_models_PlayerCoordinatesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_request_models_PlayerCoordinatesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_models_PlayerCoordinatesRequest_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
